module.exports = {
	ERROR_REDIS: 'ERROR_REDIS',
	ERROR_MONGO: 'ERROR_MONGO',
	ERROR_ELASTIC: 'ERROR_ELASTIC',
	SUCCESS_CODE: 200,
	ERROR_CODE: 500,
	LANGUAGE: /^(en|EN|vi|VI)$/,
	VI: 'VI',
	SRV_ACCOUNT: 'srv_account',
}