package com.springboot.api;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "TravelBuddyTripSectors")
public class TravelBuddyTripSectors {
	private String travelId;
	private String originCity;
	private String destinationCity;
	private String airline;
	
	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	public String getTravelId() {
		return travelId;
	}
	
	public void setTravelId(String travelId) {
		this.travelId = travelId;
	}
	
	@DynamoDBAttribute
	public String getOriginCity() {
		return originCity;
	}
	public void setOriginCity(String originCity) {
		this.originCity = originCity;
	}
	
	@DynamoDBAttribute
	public String getDestinationCity() {
		return destinationCity;
	}
	public void setDestinationCity(String destinationCity) {
		this.destinationCity = destinationCity;
	}
	
	@DynamoDBAttribute
	public String getAirline() {
		return airline;
	}
	public void setAirline(String airline) {
		this.airline = airline;
	}
	
	
	
}
