## Build locally
# docker build . -t nextapp
## Run locally
# docker run -it -p 8080:3000 nextapp

FROM public.ecr.aws/bitnami/node:12-prod
WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn

COPY . .

RUN yarn build
EXPOSE 3000
CMD ["yarn", "start"]